"""AI business service layer — summary, tags, analysis, briefing, knowledge matching."""

from __future__ import annotations

import json
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from typing import Any

from app.models.knowledge import KnowledgeEntry
from app.services.ai_provider_adapter import AIProviderAdapter
from app.utils.errors import AIServiceError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

VALID_MONITOR_GROUPS = {"Luxury", "Sports", "Outdoor", "Rap&Culture"}

VALID_CONTENT_TYPES = {
    "联名",
    "新品",
    "秀场",
    "广告",
    "lookbook",
    "品牌动态",
    "快闪展览",
    "穿搭",
    "球鞋配饰",
    "行业趋势",
}


@dataclass
class ArticleTags:
    """Structured tags extracted from an article by AI."""

    brands: list[str] = field(default_factory=list)
    monitor_groups: list[str] = field(default_factory=list)
    content_types: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)


@dataclass
class DeepAnalysisResult:
    """Structured deep analysis report generated by AI."""

    importance: str = ""
    industry_background: str = ""
    follow_up_suggestions: str = ""


@dataclass
class ArticleSummary:
    """Lightweight article representation used as input for daily briefing."""

    id: str
    title: str
    summary: str
    monitor_group: str


@dataclass
class DailyBriefingContent:
    """Structured daily briefing content matching the JSONB schema."""

    summary: str = ""
    sections: list[dict[str, Any]] = field(default_factory=list)
    trends: list[str] = field(default_factory=list)
    follow_up_suggestions: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "sections": self.sections,
            "trends": self.trends,
            "follow_up_suggestions": self.follow_up_suggestions,
        }


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------


class AIServiceBase(ABC):
    """AI service abstract base class."""

    def __init__(self, provider_adapter: AIProviderAdapter) -> None:
        self.provider_adapter = provider_adapter

    @abstractmethod
    async def generate_summary(self, title: str, content: str, source_lang: str) -> str:
        """生成中文摘要（不超过 200 字）"""

    @abstractmethod
    async def extract_tags(
        self,
        title: str,
        content: str,
        brand_pool: list[str],
        keyword_pool: list[str],
    ) -> ArticleTags:
        """提取标签（品牌、监控组、内容类型）"""

    @abstractmethod
    async def generate_deep_analysis(
        self, title: str, summary: str, tags: ArticleTags
    ) -> DeepAnalysisResult:
        """生成深度分析报告（重要性、背景、跟进方向）"""

    @abstractmethod
    async def generate_daily_briefing(
        self, articles: list[ArticleSummary], briefing_date: date
    ) -> DailyBriefingContent:
        """生成每日简报"""

    @abstractmethod
    async def generate_history_analysis(
        self, article_summary: str, knowledge_entries: list[KnowledgeEntry]
    ) -> str:
        """生成历史背景分析"""

    @abstractmethod
    async def match_knowledge_entries(
        self, article_tags: ArticleTags, knowledge_entries: list[KnowledgeEntry]
    ) -> list[KnowledgeEntry]:
        """匹配相关知识条目"""


# ---------------------------------------------------------------------------
# Concrete implementation
# ---------------------------------------------------------------------------


class AIService(AIServiceBase):
    """Concrete AI business service.

    Each method builds an appropriate prompt and calls the AI via
    ``AIProviderAdapter.chat_completion``.  Chinese articles skip the
    translation / summary-generation step (requirement 2.4).
    """

    # ------------------------------------------------------------------
    # generate_summary
    # ------------------------------------------------------------------

    async def generate_summary(self, title: str, content: str, source_lang: str) -> str:
        """Generate a Chinese summary (max 200 chars).

        If *source_lang* starts with ``"zh"``, the original content is
        returned directly (truncated to 200 characters) without calling AI.
        """
        if source_lang.startswith("zh"):
            # Chinese content — use directly, truncate if needed
            text = content.strip() if content else title.strip()
            return text[:200]

        prompt = (
            "你是一位专业的时尚潮流资讯编辑。请将以下英文时尚资讯整理成一段简洁的中文摘要，"
            "要求：\n"
            "1. 摘要必须使用中文\n"
            "2. 摘要不超过 200 个字符\n"
            "3. 保留关键信息：品牌名称、事件、时间、地点等\n"
            "4. 语言风格专业、简洁\n\n"
            f"标题：{title}\n\n"
            f"内容：{content}\n\n"
            "请直接输出中文摘要，不要包含任何前缀或解释。"
        )

        messages = [{"role": "user", "content": prompt}]
        result = await self.provider_adapter.chat_completion(messages, temperature=0.3)
        # Ensure the summary respects the 200-char limit
        return result.strip()[:200]

    # ------------------------------------------------------------------
    # extract_tags
    # ------------------------------------------------------------------

    async def extract_tags(
        self,
        title: str,
        content: str,
        brand_pool: list[str],
        keyword_pool: list[str],
    ) -> ArticleTags:
        """Extract structured tags from an article via AI."""

        brand_list_str = "、".join(brand_pool) if brand_pool else "（无预设品牌）"
        keyword_list_str = "、".join(keyword_pool) if keyword_pool else "（无预设关键词）"
        monitor_groups_str = "、".join(sorted(VALID_MONITOR_GROUPS))
        content_types_str = "、".join(sorted(VALID_CONTENT_TYPES))

        prompt = (
            "你是一位专业的时尚潮流资讯分析师。请根据以下资讯内容提取标签信息。\n\n"
            f"标题：{title}\n"
            f"内容：{content}\n\n"
            "请从以下维度提取标签，以 JSON 格式返回：\n\n"
            f"1. brands — 品牌名称，只能从以下品牌池中选择：{brand_list_str}\n"
            f"2. monitor_groups — 监控组分类，只能从以下选项中选择：{monitor_groups_str}\n"
            f"3. content_types — 内容类型，只能从以下选项中选择：{content_types_str}\n"
            f"4. keywords — 关键词，优先从以下关键词池中选择：{keyword_list_str}；"
            "如果资讯涉及池外的重要关键词也可以补充\n\n"
            "返回格式（严格 JSON）：\n"
            '{"brands": [...], "monitor_groups": [...], "content_types": [...], "keywords": [...]}\n\n'
            "注意：\n"
            "- brands 必须是品牌池中存在的品牌，不要编造\n"
            "- monitor_groups 和 content_types 必须是给定选项中的值\n"
            "- 每个维度可以有多个值，也可以为空数组\n"
            "- 只返回 JSON，不要包含其他文字"
        )

        messages = [{"role": "user", "content": prompt}]
        result = await self.provider_adapter.chat_completion(messages, temperature=0.2)

        return self._parse_tags(result, brand_pool)

    @staticmethod
    def _parse_tags(raw: str, brand_pool: list[str]) -> ArticleTags:
        """Parse AI response into an ``ArticleTags`` instance.

        Gracefully handles malformed JSON by returning empty tags.
        Filters brands to only those present in the brand pool and
        validates monitor_groups and content_types against allowed sets.
        """
        try:
            # Strip markdown code fences if present
            text = raw.strip()
            if text.startswith("```"):
                lines = text.split("\n")
                # Remove first and last lines (code fences)
                lines = [l for l in lines if not l.strip().startswith("```")]
                text = "\n".join(lines)
            data = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            logger.warning("Failed to parse AI tag response: %s", raw[:200])
            return ArticleTags()

        brand_pool_set = {b.lower() for b in brand_pool}

        brands = [
            b
            for b in data.get("brands", [])
            if isinstance(b, str) and b.lower() in brand_pool_set
        ]
        monitor_groups = [
            g
            for g in data.get("monitor_groups", [])
            if isinstance(g, str) and g in VALID_MONITOR_GROUPS
        ]
        content_types = [
            t
            for t in data.get("content_types", [])
            if isinstance(t, str) and t in VALID_CONTENT_TYPES
        ]
        keywords = [
            k for k in data.get("keywords", []) if isinstance(k, str) and k
        ]

        return ArticleTags(
            brands=brands,
            monitor_groups=monitor_groups,
            content_types=content_types,
            keywords=keywords,
        )

    # ------------------------------------------------------------------
    # generate_deep_analysis
    # ------------------------------------------------------------------

    async def generate_deep_analysis(
        self, title: str, summary: str, tags: ArticleTags
    ) -> DeepAnalysisResult:
        """Generate a deep analysis report for an article."""

        tags_str = (
            f"品牌：{', '.join(tags.brands) if tags.brands else '无'}\n"
            f"监控组：{', '.join(tags.monitor_groups) if tags.monitor_groups else '无'}\n"
            f"内容类型：{', '.join(tags.content_types) if tags.content_types else '无'}\n"
            f"关键词：{', '.join(tags.keywords) if tags.keywords else '无'}"
        )

        prompt = (
            "你是一位资深的时尚行业分析师。请对以下资讯进行深度分析。\n\n"
            f"标题：{title}\n"
            f"摘要：{summary}\n"
            f"标签信息：\n{tags_str}\n\n"
            "请从以下三个维度进行分析，以 JSON 格式返回：\n\n"
            "1. importance — 这条资讯为什么重要？对行业有什么影响？\n"
            "2. industry_background — 相关的行业背景和上下文是什么？\n"
            "3. follow_up_suggestions — 作为潮流编辑，有哪些值得跟进的方向？\n\n"
            "返回格式（严格 JSON）：\n"
            '{"importance": "...", "industry_background": "...", "follow_up_suggestions": "..."}\n\n'
            "注意：\n"
            "- 每个字段都必须非空，使用中文回答\n"
            "- 分析要专业、有深度\n"
            "- 只返回 JSON，不要包含其他文字"
        )

        messages = [{"role": "user", "content": prompt}]
        result = await self.provider_adapter.chat_completion(messages, temperature=0.4)

        return self._parse_deep_analysis(result)

    @staticmethod
    def _parse_deep_analysis(raw: str) -> DeepAnalysisResult:
        """Parse AI response into a ``DeepAnalysisResult``.

        Falls back to using the entire raw text for all fields if parsing
        fails, ensuring the result always has non-empty fields.
        """
        try:
            text = raw.strip()
            if text.startswith("```"):
                lines = text.split("\n")
                lines = [l for l in lines if not l.strip().startswith("```")]
                text = "\n".join(lines)
            data = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            logger.warning("Failed to parse deep analysis response: %s", raw[:200])
            # Fallback: use raw text for all fields
            fallback = raw.strip() or "分析生成失败，请重试"
            return DeepAnalysisResult(
                importance=fallback,
                industry_background=fallback,
                follow_up_suggestions=fallback,
            )

        importance = str(data.get("importance", "")).strip()
        industry_background = str(data.get("industry_background", "")).strip()
        follow_up_suggestions = str(data.get("follow_up_suggestions", "")).strip()

        # Ensure all fields are non-empty
        fallback = raw.strip() or "分析生成失败，请重试"
        return DeepAnalysisResult(
            importance=importance or fallback,
            industry_background=industry_background or fallback,
            follow_up_suggestions=follow_up_suggestions or fallback,
        )

    # ------------------------------------------------------------------
    # generate_daily_briefing
    # ------------------------------------------------------------------

    async def generate_daily_briefing(
        self, articles: list[ArticleSummary], briefing_date: date
    ) -> DailyBriefingContent:
        """Generate a daily briefing from a list of article summaries."""

        if not articles:
            return DailyBriefingContent(
                summary=f"{briefing_date.isoformat()} 当日无新增资讯。",
                sections=[],
                trends=["当日无新增资讯"],
                follow_up_suggestions=["关注后续资讯更新"],
            )

        # Group articles by monitor group for the prompt
        grouped: dict[str, list[ArticleSummary]] = {}
        for article in articles:
            group = article.monitor_group or "其他"
            grouped.setdefault(group, []).append(article)

        articles_text_parts: list[str] = []
        for group_name, group_articles in grouped.items():
            articles_text_parts.append(f"\n【{group_name}】")
            for a in group_articles:
                articles_text_parts.append(f"- [{a.id}] {a.title}：{a.summary}")

        articles_text = "\n".join(articles_text_parts)

        prompt = (
            "你是一位专业的时尚潮流资讯编辑。请根据以下当日资讯生成一份每日潮流简报。\n\n"
            f"日期：{briefing_date.isoformat()}\n"
            f"当日资讯（共 {len(articles)} 条）：\n{articles_text}\n\n"
            "请以 JSON 格式生成简报，包含以下内容：\n\n"
            "1. summary — 当日总体概述（一段话总结当日重点）\n"
            "2. sections — 按监控组分类的重点资讯，每个 section 包含：\n"
            '   - monitor_group: 监控组名称\n'
            '   - highlights: 重点资讯数组，每条包含 article_id、title、summary\n'
            "3. trends — 值得关注的趋势和热点（字符串数组）\n"
            "4. follow_up_suggestions — 编辑建议跟进方向（字符串数组）\n\n"
            "返回格式（严格 JSON）：\n"
            "{\n"
            '  "summary": "...",\n'
            '  "sections": [\n'
            '    {\n'
            '      "monitor_group": "Luxury",\n'
            '      "highlights": [\n'
            '        {"article_id": "uuid", "title": "...", "summary": "..."}\n'
            "      ]\n"
            "    }\n"
            "  ],\n"
            '  "trends": ["...", "..."],\n'
            '  "follow_up_suggestions": ["...", "..."]\n'
            "}\n\n"
            "注意：\n"
            "- 使用中文撰写\n"
            "- article_id 使用资讯前面方括号中的 ID\n"
            "- 每个字段都不能为空\n"
            "- 只返回 JSON，不要包含其他文字"
        )

        messages = [{"role": "user", "content": prompt}]
        result = await self.provider_adapter.chat_completion(
            messages, temperature=0.4
        )

        return self._parse_daily_briefing(result, briefing_date)

    @staticmethod
    def _parse_daily_briefing(raw: str, briefing_date: date) -> DailyBriefingContent:
        """Parse AI response into a ``DailyBriefingContent``."""
        try:
            text = raw.strip()
            if text.startswith("```"):
                lines = text.split("\n")
                lines = [l for l in lines if not l.strip().startswith("```")]
                text = "\n".join(lines)
            data = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            logger.warning("Failed to parse daily briefing response: %s", raw[:200])
            return DailyBriefingContent(
                summary=raw.strip()[:500] or f"{briefing_date.isoformat()} 简报生成失败",
                sections=[],
                trends=["简报解析失败"],
                follow_up_suggestions=["请重新生成简报"],
            )

        summary = str(data.get("summary", "")).strip()
        sections = data.get("sections", [])
        trends = data.get("trends", [])
        follow_up_suggestions = data.get("follow_up_suggestions", [])

        # Validate sections structure
        valid_sections: list[dict[str, Any]] = []
        if isinstance(sections, list):
            for section in sections:
                if isinstance(section, dict) and "monitor_group" in section:
                    highlights = section.get("highlights", [])
                    if isinstance(highlights, list):
                        valid_sections.append(
                            {
                                "monitor_group": str(section["monitor_group"]),
                                "highlights": [
                                    {
                                        "article_id": str(h.get("article_id", "")),
                                        "title": str(h.get("title", "")),
                                        "summary": str(h.get("summary", "")),
                                    }
                                    for h in highlights
                                    if isinstance(h, dict)
                                ],
                            }
                        )

        valid_trends = [str(t) for t in trends if isinstance(t, str) and t]
        valid_suggestions = [
            str(s) for s in follow_up_suggestions if isinstance(s, str) and s
        ]

        return DailyBriefingContent(
            summary=summary or f"{briefing_date.isoformat()} 每日潮流简报",
            sections=valid_sections,
            trends=valid_trends or ["暂无趋势分析"],
            follow_up_suggestions=valid_suggestions or ["暂无跟进建议"],
        )

    # ------------------------------------------------------------------
    # generate_history_analysis
    # ------------------------------------------------------------------

    async def generate_history_analysis(
        self, article_summary: str, knowledge_entries: list[KnowledgeEntry]
    ) -> str:
        """Generate a historical context analysis for an article."""

        if not knowledge_entries:
            return ""

        knowledge_text_parts: list[str] = []
        for entry in knowledge_entries:
            brands_str = ", ".join(
                b.brand_name for b in (entry.brands or [])
            )
            keywords_str = ", ".join(
                k.keyword for k in (entry.keywords or [])
            )
            knowledge_text_parts.append(
                f"- 【{entry.category}】{entry.title}\n"
                f"  摘要：{entry.summary or '无'}\n"
                f"  关联品牌：{brands_str or '无'}\n"
                f"  关联关键词：{keywords_str or '无'}"
            )

        knowledge_text = "\n".join(knowledge_text_parts)

        prompt = (
            "你是一位资深的时尚行业历史研究者。请根据以下资讯摘要和相关知识库条目，"
            "分析这条资讯的历史背景和意义。\n\n"
            f"资讯摘要：{article_summary}\n\n"
            f"相关知识库条目：\n{knowledge_text}\n\n"
            "请撰写一段历史背景分析，要求：\n"
            "1. 使用中文\n"
            "2. 结合知识库中的历史信息解释这条资讯的背景\n"
            "3. 说明这条资讯在行业历史脉络中的位置和意义\n"
            "4. 语言专业、有深度\n\n"
            "请直接输出分析文本，不要包含任何前缀或解释。"
        )

        messages = [{"role": "user", "content": prompt}]
        result = await self.provider_adapter.chat_completion(messages, temperature=0.4)
        return result.strip()

    # ------------------------------------------------------------------
    # match_knowledge_entries (non-AI, tag-based matching)
    # ------------------------------------------------------------------

    async def match_knowledge_entries(
        self, article_tags: ArticleTags, knowledge_entries: list[KnowledgeEntry]
    ) -> list[KnowledgeEntry]:
        """Match knowledge entries based on shared brands or keywords.

        This is a non-AI method — it checks for overlap between the
        article's tags and each knowledge entry's associated brands and
        keywords.
        """
        article_brands = {b.lower() for b in article_tags.brands}
        article_keywords = {k.lower() for k in article_tags.keywords}

        matched: list[KnowledgeEntry] = []
        for entry in knowledge_entries:
            entry_brands = {
                b.brand_name.lower() for b in (entry.brands or [])
            }
            entry_keywords = {
                k.keyword.lower() for k in (entry.keywords or [])
            }

            # Match if any brand or keyword overlaps
            if (article_brands & entry_brands) or (article_keywords & entry_keywords):
                matched.append(entry)

        return matched
